Catkin-ProjectName: ecto_ros
Version: 0.2.3
Description: A set of generic cells to interact with ROS
Author: Ethan Rublee <erublee@willowgarage.com>, Vincent Rabaud <vrabaud@willowgarage.com>
Maintainer:  Vincent Rabaud <vrabaud@willowgarage.com>
Homepage:  http://ecto.willowgarage.com/recognition

Depends: catkin, ecto

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
