Catkin-ProjectName: ecto_ros
Version: 0.3.0
Description: A set of generic cells to interact with ROS
Author: Ethan Rublee <erublee@willowgarage.com>, Vincent Rabaud <vrabaud@willowgarage.com>
Maintainer:  Vincent Rabaud <vrabaud@willowgarage.com>
Homepage:  http://ecto.willowgarage.com/recognition

Depends: catkin, ecto, std_msgs, sensor_msgs, geometry_msgs, nav_msgs

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
